FROM adoptopenjdk/openjdk8 as BASE

ARG SBT_VERSION=1.5.5

# Install sbt
RUN \
  mkdir /working/ && \
  cd /working/ && \
  curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  cd && \
  rm -r /working/ && \
  sbt sbtVersion


FROM BASE as COMPILED

WORKDIR /src
COPY ./ .
RUN sbt compile && sbt assembly


FROM adoptopenjdk/openjdk8
COPY --from=COMPILED /src/target/scala-3.1.0/main.jar /main.jar
COPY input.txt .
CMD java -jar /main.jar