FROM adoptopenjdk/openjdk8 as base

ARG SBT_VERSION=1.5.5

# Install sbt
RUN \
  mkdir /working/ && \
  cd /working/ && \
  curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  cd && \
  rm -r /working/ && \
  sbt sbtVersion


FROM base as compiled

WORKDIR /src
COPY ./ .
RUN sbt compile && sbt assembly

FROM ghcr.io/graalvm/graalvm-ce:latest as graal
WORKDIR /src
RUN gu install native-image
COPY --from=compiled /src/target/scala-3.1.0/main.jar /main.jar
RUN native-image --static --verbose --allow-incomplete-classpath --report-unsupported-elements-at-runtime --no-fallback --initialize-at-build-time -jar /main.jar app

FROM alpine
WORKDIR /src
COPY --from=graal /src/app app
COPY input.txt .
CMD ./app